# Render deployment configuration (FULL VERSION with Voice Features)
services:
  - type: web
    name: english-learning-app
    env: python
    plan: free
    buildCommand: |
      # Update package lists
      apt-get update
      # Install Chromium instead of Chrome (more reliable on Ubuntu/Debian)
      apt-get install -y chromium-browser chromium-chromedriver
      # Verify Chromium installation
      which chromium-browser
      chromium-browser --version
      # Create Chrome compatibility symlinks
      ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome-stable
      ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
      ln -sf /usr/bin/chromium-browser /usr/local/bin/google-chrome
      # Verify symlinks
      which google-chrome-stable
      which google-chrome
      google-chrome --version
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: SELENIUM_HEADLESS
        value: true
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium-browser
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
