# Render deployment configuration (FULL VERSION with Voice Features)
services:
  - type: web
    name: english-learning-app
    env: python
    plan: free
    buildCommand: |
      # Show current user and permissions
      whoami
      id
      # Update package lists with error checking
      apt-get update || echo "apt-get update failed"
      # Try installing Chromium via snap first (more reliable)
      snap install chromium || echo "snap chromium install failed"
      # Check snap installation
      snap list | grep chromium || echo "no chromium snap found"
      ls -la /snap/bin/chromium* || echo "no chromium in /snap/bin"
      # Try traditional apt installation as fallback
      apt-get install -y chromium-browser || echo "apt chromium install failed"
      # Check what was actually installed
      dpkg -l | grep chromium || echo "no chromium packages found"
      # Manual verification of all possible locations
      ls -la /usr/bin/chromium* || echo "no chromium binaries in /usr/bin"
      ls -la /snap/bin/chromium* || echo "no chromium binaries in /snap/bin"
      ls -la /usr/bin/google-chrome* || echo "no chrome binaries in /usr/bin"
      # Create Chrome compatibility symlinks for any found chromium
      CHROMIUM_PATH=""
      if [ -f /snap/bin/chromium ]; then
        CHROMIUM_PATH="/snap/bin/chromium"
        echo "Found Chromium via snap"
      elif [ -f /usr/bin/chromium-browser ]; then
        CHROMIUM_PATH="/usr/bin/chromium-browser"
        echo "Found Chromium via apt"
      elif [ -f /usr/bin/chromium ]; then
        CHROMIUM_PATH="/usr/bin/chromium"
        echo "Found Chromium as chromium"
      fi
      
      if [ -n "$CHROMIUM_PATH" ]; then
        ln -sf "$CHROMIUM_PATH" /usr/bin/google-chrome-stable
        ln -sf "$CHROMIUM_PATH" /usr/bin/google-chrome
        ln -sf "$CHROMIUM_PATH" /usr/local/bin/google-chrome
        echo "Chromium symlinks created using $CHROMIUM_PATH"
      else
        echo "❌ No Chromium found anywhere"
      fi
      # Final verification
      which chromium-browser || echo "chromium-browser not in PATH"
      which chromium || echo "chromium not in PATH"
      which google-chrome || echo "google-chrome not in PATH"
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: SELENIUM_HEADLESS
        value: true
      - key: GOOGLE_CHROME_BIN
        value: /snap/bin/chromium
      - key: CHROMEDRIVER_PATH
        value: /snap/bin/chromedriver
