# Render deployment configuration (FULL VERSION with Voice Features)
services:
  - type: web
    name: english-learning-app
    env: python
    plan: free
    buildCommand: |
      # Update package lists and install prerequisites
      apt-get update
      apt-get install -y wget gnupg2 software-properties-common apt-transport-https ca-certificates curl
      # Install Chrome with comprehensive approach for Render
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg
      sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      apt-get update
      apt-get install -y google-chrome-stable
      # Create symlink for common chrome command
      ln -sf /usr/bin/google-chrome-stable /usr/bin/google-chrome
      # Verify Chrome installation with multiple checks
      which google-chrome-stable
      which google-chrome  
      google-chrome-stable --version
      google-chrome --version
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: SELENIUM_HEADLESS
        value: true
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
