# Render deployment configuration (FULL VERSION with Voice Features)
services:
  - type: web
    name: english-learning-app
    env: python
    plan: free
    buildCommand: |
      # Update package lists first
      apt-get update
      # Install prerequisites
      apt-get install -y wget gnupg2 unzip curl
      # Download and install Chrome directly from .deb package (more reliable for Render)
      wget -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      # Install Chrome dependencies first
      apt-get install -y --fix-missing fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libdrm2 libgtk-3-0 libnspr4 libnss3 lsb-release xdg-utils libxss1 libgconf-2-4
      # Install Chrome package
      dpkg -i /tmp/google-chrome.deb || apt-get install -fy
      # Verify installation
      which google-chrome-stable
      google-chrome-stable --version
      # Create symlinks for compatibility
      ln -sf /usr/bin/google-chrome-stable /usr/local/bin/google-chrome
      ln -sf /usr/bin/google-chrome-stable /usr/bin/google-chrome
      # Verify symlinks
      which google-chrome
      google-chrome --version
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: SELENIUM_HEADLESS
        value: true
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
